config/routes.rb
EZNotes::Application.routes.draw do
  resources :users 
  resources :sessions,  only: [:new, :create, :destroy]
  resources :notes,     only: [:create, :destroy]
  resources :courses,   only: [:show, :index, :create, :destroy, :update] 
  resources :course_imports, only: [:create, :new]
  resources :registrations, only: [:index, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update ]
  resources :accomodations, only: [:new, :create, :index]
  
  root to: 'static_pages#home'

  match '/notes/:id/:style.:extension', to: 'notes#download', via: 'get'

  match '/signup_noteuser',  to: 'users#new_noteuser',          via: 'get'
  match '/signup_notetaker',  to: 'users#new_notetaker',          via: 'get'
  match '/signin',  to: 'sessions#new',       via: 'get'
  match '/signout', to: 'sessions#destroy',   via: 'delete'
  match '/delete_all_courses', to: 'courses#delete_all_courses',        via: 'delete'
  match '/delete_accommodations', to: 'accomodations#delete_accommodations',        via: 'delete'

  match '/create_admin', to: 'users#create_admin',        via: 'put'

  match '/import_accomodations', to: 'accomodations#import', via: 'post'

  match '/help', to: 'static_pages#help',	via:'get'
  match '/about', to: 'static_pages#about',	via:'get'
  match '/contact', to: 'static_pages#contact',	via:'get'
end

app/models/accomodation.rb
# == Schema Information
#
# Table name: accomodations
#
#  id          :integer          not null, primary key
#  student_id  :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  note_taking :string(255)
#

class Accomodation < ActiveRecord::Base

  VALID_ID_REGEX = /\A\d+\z/i
  validates :student_id, presence: { message: "ID cannot be blank"} ,
                          format: { with: VALID_ID_REGEX, 
                           message: "ID is incorrect format; must be a 9 digit number" }, 
                          uniqueness: true,
                          length: { is: 9 }

  default_scope -> { order('created_at ASC') }

  def self.import(file)
    spreadsheet = open_spreadsheet(file)

    # Find the header in the spreadsheet. WE cannot assume the header is in a particular
    # row in the spreadsheet
    header = []
    (2..spreadsheet.last_row).each do |i|
      if spreadsheet.row(i)[0] == "ID"
        header = spreadsheet.row(i)
        break
      end
    end

    # for each student in the spreadsheet store the accomodations
    accomodations = Hash.new   
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      if row.values != header and not row["ID"].nil? and not row["GENERAL ACCOMODATION CODE"].nil?
        
        student_id = row["ID"]
        accomodation_code = row["GENERAL ACCOMODATION CODE"].upcase

        if accomodations[student_id].nil?
          accomodations[student_id] = accomodation_code
        else
          accomodations[student_id] = accomodations[student_id] + "," + accomodation_code
        end
      end
    end

    # for each student find out if that student is already in our accomodations
    # database and compare their current accomodations with the new ones from the
    # spreadsheet
    accomodations.keys.each do |key|
      accomodation = find_by(student_id: key) || new
      accomodation.student_id = key
      if accomodation.note_taking.nil?
        accomodation.note_taking = accomodations[key]
      else
        accomodations[key].split(',').each do |code|
          if accomodation.note_taking.split(',').include?(code)
            accomodation.note_taking = accomodation.note_taking.split(',').delete(code)
          else
            accomodation.note_taking = accomodation.note_taking + "," + code
          end
        end
      end
      accomodation.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv' then Roo::CSV.new(file.path, csv_options: {encoding: Encoding::ISO_8859_1})
    when '.xls' then Roo::Excel.new(file.path, {packed: nil, file_warning: :ignore})
    when '.xlsx' then Roo::Excelx.new(file.path, {packed: nil, file_warning: :ignore})
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/accomodations_controller.rb
class AccomodationsController < ApplicationController
   before_action :signed_in_user 
   before_action :admin_user 

   def index
      @accomodations = Accomodation.all
   end

   def new
      @accomodation = Accomodation.new
   end

   def create
      @accomodation = Accomodation.new(accomodation_params)
      if @accomodation.save
         flash[:success] = "Accomodation added"
         redirect_to accomodations_path
      else
         render 'new'
      end
   end

   def import
      file = params[:file]
      if file.nil?
         flash.now[:error] = "Empty file passed"
         render :new
      elsif File.extname(file.original_filename) != ".csv" and File.extname(file.original_filename) != ".xlsx"
         flash.now[:error] = "Incorrect file format #{File.extname(file.original_filename)}: only .csv or .xlsx files allowed"
         render 'new'
      else
         Accomodation.import(file)
         flash[:success] = "Successfully imported accomodations"
         redirect_to accomodations_path
      end
   end

   def delete_accommodations
      if Accomodation.delete_all
         flash[:success] = "Deleted all Accomodations"
         redirect_to :back
      else
         flash[:error] = "Could not delete accomodations"
      end
   end

   private

      def accomodation_params
         params.require(:accomodation).permit(:student_id, :note_taking)
      end

      # Before filters

      def admin_user
         redirect_to root_path, notice: "You are not authorized to view this page" unless current_user.admin?
      end
end

app/helpers/accomodations_helper.rb
module AccomodationsHelper
end

app/views/accomodations/_accomodation.html.erb
<tr id="<%= accomodation.id %>">
   <td>
      <%= "#{accomodation.student_id}" %>
   </td>
   <td>
      <% user =  User.find_by(student_id: accomodation.student_id, note_taker: false) %>
      <% if user %>
         <%= link_to "#{user.name}", edit_user_path(user) %>
      <% else %>
         Not Registered
      <% end %>
   </td>
   <td><%= "#{accomodation.note_taking}" %></td>
   <td>
      <% if accomodation.note_taking.split(',').include?('GC') or accomodation.note_taking.split(',').include?('GM')%>
         <i class="icon-check text-success"> YES</i>
      <% else %>
         <i class="icon-check-empty text-error"> NO</i>
      <% end %>
   </td>
</tr>

app/views/accomodations/index.html.erb
<% provide(:title, 'Accommodations') %>
<aside class="row-fluid">
   <section>
         <%= link_to " Import Accomodations", new_accomodation_path, class: "btn btn-inverse icon-upload-alt icon-large" %>
         <%= link_to " Delete All Accomodations", 'delete_accommodations', method: :delete, data: { confirm: "WARNING This will delete all accomodations!!!" },class: "btn btn-danger icon-trash icon-large" %>
   </section>
   <section>
      <form class="form-search offset5">
         <input type="text" name="filter" value="" id="filter" class="input-large search-query" />
         <label for="filter" class="icon-filter icon-large"> Filter</label>
      </form>
   </section>
</aside>
<article class="span10 offset3">
   <table cellpadding="1" cellspacing="1" id="accomodationsTable" class="table table-bordered table-hover">
      <caption class="alert alert-info"> 
         <h2> For all students registered with the OSD display their accomodations </h2>
      </caption>
      <thead>
         <tr>
            <th class="sortable icon-sort-by-alphabet sorted-asc span3"> Registered with OSD (<%= @accomodations.count %>)</th>
            <th class="sortable icon-sort-by-alphabet sorted-asc span3"> Registered with Website?</th>
            <th class="sortable icon-sort-by-alphabet sorted-asc span3"> Accomodations</th>
            <th class="sortable icon-sort-by-alphabet sorted-asc span4"> Require Note-taking? (<strong class="text-success icon-check"> <%= @accomodations.where("note_taking SIMILAR TO ?", "%(GC|GM)%").count %></strong> | <strong class="text-error icon-check-empty"> <%= @accomodations.where("note_taking NOT SIMILAR TO ?", "%(GC|GM)%").count %></strong>)</th>
         </tr>
      </thead>
      <tbody>
         <%= render @accomodations %>
      </tbody>
   </table>
</article>

app/views/accomodations/new.html.erb
<% provide(:title, 'Accommodation Import') %>
<article class="row-fluid">
   <h1 class="center">Accommodation Import</h1>
   <section class="alert alert-block alert-info span8 offset2">
      <header>
         An Excel spreadsheet or a CSV file can be used to import records.
      </header>

      <p>
         The following columns are allowed. It is assumed that the student id is in a column called "ID" and the accommodation code is in a column called "GENERAL ACCOMODATION CODE". It is also assumed that the accomodation code for note_taking is either "GC" or "GM"
         <ul>
            <li>
              <strong>student_id</strong> -
              String
            </li>
            <li>
              <strong>accommodation code</strong> -
              String
            </li>
         </ul>
      </p>
   </section>

   <section class="well span4 offset4">
      <%= form_tag import_accomodations_path, multipart: true do %>

         <fieldset>
          <%= label_tag :file, " File", class: "icon-folder-open" %>
          <p class="controls">
            <%= file_field_tag :file, accept: 'text/csv application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet application/vnd.openxmlformats-officedocument.spreadsheetml.template', multiple: true, class: "input-xlarge"%>
          </p>
         </fieldset>

         <fieldset>
            <%= button_tag(type: 'submit', class: "btn btn-large btn-inverse icon-upload-alt icon-large") do %>
               Import
            <% end %>
         </fieldset> 
      <% end %>
   </section>
</article>