config/routes.rb
EZNotes::Application.routes.draw do
  resources :users 
  resources :sessions,  only: [:new, :create, :destroy]
  resources :notes,     only: [:create, :destroy]
  resources :courses,   only: [:show, :index, :create, :destroy, :update] 
  resources :course_imports, only: [:create, :new]
  resources :registrations, only: [:index, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update ]
  resources :accomodations, only: [:new, :create, :index]
  
  root to: 'static_pages#home'

  match '/notes/:id/:style.:extension', to: 'notes#download', via: 'get'

  match '/signup_noteuser',  to: 'users#new_noteuser',          via: 'get'
  match '/signup_notetaker',  to: 'users#new_notetaker',          via: 'get'
  match '/signin',  to: 'sessions#new',       via: 'get'
  match '/signout', to: 'sessions#destroy',   via: 'delete'
  match '/delete_all_courses', to: 'courses#delete_all_courses',        via: 'delete'
  match '/delete_accommodations', to: 'accomodations#delete_accommodations',        via: 'delete'

  match '/create_admin', to: 'users#create_admin',        via: 'put'

  match '/import_accomodations', to: 'accomodations#import', via: 'post'

  match '/help', to: 'static_pages#help',	via:'get'
  match '/about', to: 'static_pages#about',	via:'get'
  match '/contact', to: 'static_pages#contact',	via:'get'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  email                  :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  student_id             :string(255)
#  remember_token         :string(255)
#  admin                  :boolean          default(FALSE)
#  note_taker             :boolean          default(FALSE)
#  password_digest        :string(255)
#  password_reset_token   :string(255)
#  password_reset_sent_at :datetime
#  approved               :boolean          default(FALSE)
#

class User < ActiveRecord::Base
   has_many :notes, dependent: :destroy
   has_many :registrations, foreign_key: "user_id", dependent: :destroy
   has_many :registered_courses, through: :registrations, source: :course

   before_save { email.downcase! }
   before_create :create_remember_token

   default_scope -> { order('name ASC') }

   attr_reader :course_tokens
      
   validates :name, presence: true, 
                    length: { maximum: 50 }

   VALID_EMAIL_REGEX = /\A(\w|\-)+\.([\w]+\.)?(\w|\-)+(@mail.mcgill.ca|@mcgill.ca)\z/i
   validates :email, presence: true, 
                     format: { with: VALID_EMAIL_REGEX, 
                        message: " is incorrect format must be of the form firstname.lastname@mail.mcgill.ca" },
                     uniqueness: { case_sensitive: false }

   VALID_ID_REGEX = /\A\d{9}\z/i
   validates :student_id, presence: { message: "ID cannot be blank"} ,
                          format: { with: VALID_ID_REGEX, 
                           message: "ID is incorrect format; must be a 9 digit number" }, 
                          uniqueness: true,
                          length: { is: 9 }

   has_secure_password
   VALID_PASSWORD_REGEX = /\A[^\s']+\z/
   validates :password, length: { minimum: 8 },
   format: { with: VALID_PASSWORD_REGEX, message: " is incorrect format; cannot have any spaces or quotes(')"},
   if: :password_required?


   def course_tokens=(ids)
      self.course_ids = ids.split(",")
   end

   def notetaking_for
      notetaking = []
      registered_courses.each do |course|
         if course.note_taker and course.note_taker == self
            notetaking.push course
         end
      end
      notetaking
   end

   def notes_feed
      Note.where("user_id = ?", id)
   end

   def fall_course_feed
      registered_courses.where("term = ?", "fall")
   end

   def winter_course_feed
      registered_courses.where("term = ?", "winter")
   end

   def summer_course_feed
      registered_courses.where("term = ?", "summer")
   end

   def registered_with?(course)
      registrations.find_by(course_id: course.id)
   end

   def register!(course)
      registrations.create!(course_id: course.id)
   end

   def unregister!(course)
      registrations.find_by(course_id: course.id).destroy!
   end

   def User.new_remember_token
      SecureRandom.urlsafe_base64
   end

   def User.encrypt(token)
      Digest::SHA1.hexdigest(token.to_s)
   end

   def send_password_reset
      generate_reset_token(:password_reset_token)
      self.password_reset_sent_at = Time.zone.now
      save!
      UserMailer.password_reset(self).deliver
   end

   def send_new_registration_message
      UserMailer.new_registration(self).deliver
   end

   def send_assigned_to_course_message(course)
      UserMailer.assign_notetaker(self, course).deliver
   end

   def send_notetaker_assigned(course)
      UserMailer.notify_users(self, course).deliver
   end

   def send_unassigned_from_course_message(course)
      UserMailer.unassign_notetaker(self, course).deliver
   end

   protected

      def password_required?
         !persisted? || !password.nil? || !password_confirmation.nil?
      end

   private

      def create_remember_token
         self.remember_token = User.encrypt(User.new_remember_token)
      end

      def generate_reset_token(column)
         begin
            self[column] = SecureRandom.urlsafe_base64
         end while User.exists?(column => self[column])
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user,  only: [:index, :edit, :update, :show, :destroy]
  before_action :correct_user,    only: [:edit, :update, :show]
  before_action :admin_user,      only: [:create_admin, :destroy, :index]
  before_action :limit_user,      only: [:new_noteuser, :new_notetaker, :create]

  def index
    @users = User.all
  end

  def show
		@user = User.find(params[:id])	
    @notes = @user.notes.paginate(page: params[:page])
	end

  def new_noteuser
    @user = User.new
  end

  def new_notetaker
    @user = User.new(note_taker: true)
  end

  def create
		@user = User.new(create_params)
    #accomodation = Accomodation.find_by(student_id: @user.student_id)
    #if not @user.note_taker and ( accomodation.nil? or not accomodation.note_taking)
      #flash.now[:error] = "You are not registered with the OSD to recieve note taking, hence you cannot register for this service."
      #render 'new_noteuser'
    #else
  		if @user.save
        @user.send_new_registration_message
        sign_in @user
        flash[:success] = "Welcome to EZ Notes!"
  			redirect_to root_path
  		else
        if @user.note_taker
          render 'new_notetaker'
        else
          render 'new_noteuser'
  		  end
      end
    #end
  end

  def create_admin
    @user = User.new(admin_params)
    @user.admin = true
    if @user.save
      flash[:success] = "New Admin user [ #{@user.student_id} #{@user.name} #{@user.email} created"
      redirect_to :back
    else
      full_msg = " "
      @user.errors.full_messages.each do |msg|
        full_msg = full_msg + msg + ". "
      end
      flash[:error] = "Could not create admin user. #{full_msg}"
      redirect_to :back
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update_attributes(update_params)
        # Handle a successful update
        format.html {
          flash[:success] = "Profile updated"
          if current_user.admin? and not current_user?(@user)
            redirect_to :back
          else
            sign_in @user
            redirect_to root_path
          end
        }
        format.js { render 'update', locals: { user: @user } }
      else
        format.html { render 'edit' }
        format.js { render nothing: true }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.admin? and current_user?(@user)
      flash[:error] = "Admin User cannot delete themselves!"
      redirect_to user_path(@user)
    else
      @user.destroy
      flash[:success] = "User deleted."
      redirect_to users_url
    end
  end

  private

    def update_params
      if current_user.admin?
  		  params.require(:user).permit(:name, :email, :student_id, :note_taker, :approved)
      else
        params.require(:user).permit(:name, :student_id)
      end
  	end 

    def create_params
      params.require(:user).permit(:name, :email, :student_id, :password,
                                   :password_confirmation, :note_taker)
    end

    def admin_params
      params.permit(:name, :email, :student_id, :password,
                                   :password_confirmation, :admin)
    end

    # Before filters

    def correct_user
      if User.exists?(params[:id])
        @user = User.find(params[:id])
        redirect_to root_path, notice: "You are not authorized to access this page." unless current_user?(@user) or current_user.admin?
      else
        if current_user.admin?
          flash[:error] = "User does not exist"
        else
          flash[:notice] = "You are not authorized to access this page."
        end
        redirect_to root_path
      end
    end

    def admin_user
      redirect_to root_path, notice: "You are not authorized to access this page." unless current_user.admin?
    end

    def limit_user
      if signed_in? and not current_user.admin?
        redirect_to root_path, notice: "You are not authorized to perform this action."
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_new.html.erb
<section class="well span4 offset4">
	<%= form_for @user, html: { class: "form-inline" } do |f| %>
		<legend>First, Tell Us a Bit About Yourself</legend>
		<%= render 'shared/error_messages', object: f.object %>

		<%= f.hidden_field :note_taker, value: locals[:note_taker] %>

		<fieldset name="userName" class="control-group">
			<%= f.label :name do %>
				<i class="icon-user icon-large"></i> Name
			<% end %>
			<p class="controls">
				<%= f.text_field :name, required: true, maxlength: "50", placeholder: "John Doe", autofocus: true, class: "input-xlarge" %>
			</p>
		</fieldset>

		<fieldset name="userEmail" class="control-group">
			<%= f.label :email do %>
				<i class="icon-envelope icon-large"></i> McGill Email 
			<% end %>
			<p class="controls">
				<%= f.email_field :email, required: true, 
						:'data-validation-email-message' => "Please enter a valid email", 
						:'data-validation-regex-regex' => "^[a-zA-Z0-9\-]+\\.([a-zA-Z0-9]+\\.)?[a-zA-Z0-9\-]+@mail.mcgill.ca$", 
						:'data-validation-regex-message' => "Must be of the form firstname.lastname@mail.mcgill.ca", 
						placeholder: "john.doe@mail.mcgill.ca", class: "email", id: "signup_email", class: "input-xlarge"  %>
			</p>
		</fieldset>

		<fieldset name="userID" class="control-group">
			<%= f.label :student_id do %>
				<i class="icon-credit-card icon-large"></i> McGill Student ID
			<% end %>
			<p class="controls">
				<%= f.text_field :student_id, required: true, 
				:'data-validation-regex-regex' => "^[0-9]+$", 
				:'data-validation-regex-message' => "Student ID is incorrect format; must be a 9 digit number", 
				maxLength: "9",
				minLength: "9",
				placeholder: "123456789", class: "input-xlarge"  %>
			</p>
		</fieldset>

		<fieldset name="userPassword" class="control-group">
			<%= f.label :password do %>
				<i class="icon-lock icon-large"></i> McGill Password
			<% end %>
			<p class="controls">
				<%= f.password_field :password, required: true, minLength: "8",
				:'data-validation-regex-regex' => "^[^\\s']+$", 
				:'data-validation-regex-message' => "Password is incorrect format; cannot have any spaces or quotes(')", class: "input-xlarge"  %>
			</p>
		</fieldset>

		<fieldset name="userPasswordConfirm" class="control-group">
			<%= f.label :password_confirmation do %>
				<i class="icon-lock icon-large"></i> Confirmation
			<% end %>
			<p class="controls">
				<%= f.password_field :password_confirmation, 
				:'data-validation-match-match' => "user[password]", 
				:'data-validation-match-message' => "Password confirmation must match password", class: "input-xlarge"  %>
			</p>
		</fieldset>

		<fieldset name="userButtons" class="btn-toolbar">
			<section class="btn-group">
		      <%= link_to root_path, class: "btn btn-large btn-inverse" do %>
		      	<i class="icon-remove icon-large"></i> Cancel
		      <% end %>
		   </section>
		   <section class="btn-group">
		      <%= button_tag(type: 'submit', class: "btn btn-large btn-danger") do %>
		      <i class="icon-ok icon-large"></i> Register
				<% end %>
			</section>
		</fieldset>
	<% end %>
</section>

app/views/users/_user.html.erb
<li>
   (
   <% if user.note_taker? %>
      <strong class="text-success"><i class="icon-pencil icon-large"></i> NoteTaker</strong>
   <% elsif user.admin? %>
      <strong class="text-error"><i class="icon-gears icon-large"></i> Admin</strong>
   <% else %>
      <strong class="text-warning"><i class="icon-user icon-large"></i> NoteUser</strong>
   <% end %>)
	<%= user.student_id %>
	<strong><%= link_to user.name, edit_user_path(user) %></strong>
  <% if user.note_taker?  %>
    <% if user.approved?  %>
      <i class="icon-star icon-large approve"></i>
    <% else %>
      <i class="icon-star-empty icon-large"></i>
    <% end %>
  <% end %>
	<%= user.email %>
   
	<% if current_user.admin? && !current_user?(user) %>
		<%= link_to user, method: :delete,
									  data: { confirm: "Delete user #{user.student_id} #{user.name}" }, 
                             class: "delete" do %>
        <i class="icon-trash icon-large"></i> Delete
    <% end %>
    <% if user.note_taker? %>
      <% if user.approved? %>
        <%= link_to user_path(user, user: { :approved => false }), method: :put do %>
            <i class="icon-thumbs-down icon-large"></i> Unapprove
        <% end %>
      <% else %>
        <%= link_to user_path(user, user: { :approved => true }), method: :put do %>
          <i class="icon-thumbs-up icon-large"></i> Approve
        <% end %>
      <% end %>
    <% end %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<section class="well span4 offset4">
		<%= form_for(@user, html: { class: "form-inline" } ) do |f| %>
			<legend>Update Your Profile</legend>
			<%= render 'shared/error_messages', object: f.object %>

			<fieldset class="control-group">
				<%= f.label :name, class: "control-label" do %>
					<i class="icon-user icon-large"></i> Name
				<% end %>
				<p class="controls">
					<%= f.text_field :name, autofocus: true, maxlength: "50", required: true, class: "input-xlarge" %>
				</p>
			</fieldset>

			<fieldset class="control-group">
				<%= f.label :student_id, class: "control-label" do %>
					<i class="icon-credit-card icon-large"></i> Student ID
				<% end %>
				<p class="controls">
					<%= f.text_field :student_id, required: true,
					:'data-validation-regex-regex' => "^[0-9]+$", 
					:'data-validation-regex-message' => "Student ID is incorrect format; must be a 9 digit number", 
					maxLength: "9",
					minLength: "9", class: "input-xlarge" %>
				</p>
			</fieldset>

			<% if current_user.admin? %>
				<fieldset class="control-group">
					<%= f.label :email, class: "control-label" do %>
						<i class="icon-envelope icon-large"></i> McGill Email
					<% end %>
					<p class="controls">
						<%= f.text_field :email, required: true, 
							:'data-validation-email-message' => "Please enter a valid email", 
							:'data-validation-regex-regex' => "^[a-zA-Z0-9\-]+\\.([a-zA-Z0-9]+\\.)?[a-zA-Z0-9\-]+(@mail.mcgill.ca|@mcgill.ca)$", 
							:'data-validation-regex-message' => "Must be of the form 
							firstname.lastname@mail.mcgill.ca or firstname.middleinitial.lastname@mail.mcgill.ca", class: "input-xlarge" %>
					</p>
				</fieldset>
			<% end %>

			<% if current_user.admin? and not current_user?(@user) %>
				<fieldset class="control-group">
					<p class="controls">
						<%= f.label :note_taker, class: "checkbox inline" do %>
							<i class="icon-pencil icon-large"></i> NoteTaker?
						<% end %>
					
						<%= f.check_box :note_taker %> 
					</p>
				</fieldset>
			<% end %>
			<fieldset class="control-group">
				<%= button_tag(type: 'submit', class: "btn btn-large btn-inverse") do %>
					<i class="icon-save icon-large"></i> Save changes
				<% end %>
			</fieldset>
		<% end %>
</section>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<form class="form-search offset7">
   <label for="filter"> <i class="icon-filter icon-large"></i>Filter</label>
   <input type="text" name="filter" value="" id="user_filter" class="input-large search-query" />
</form>
<article class="row-fluid">
   <aside class="span3">
      <section class="well">
         <%= form_tag('/create_admin', method: :put ) do %>
            <legend><i class="icon-plus icon-large"></i> Add Admin User</legend>

            <fieldset name="addAdminName" class="control-group">
               <%= label_tag :name, nil, class: "cus-user control-label" %>
               <p class="controls">
                  <%= text_field_tag :name, nil, maxlength: "50", placeholder: "john doe", required: true, class: "input-xlarge newAdminName" %>
               </p>
            </fieldset>

            <fieldset name="addAdminEmail" class="control-group">
               <%= label_tag :email, "McGill Email", class: "cus-mail-alt" %>
               <p class="controls">
                  <%= text_field_tag :email, nil, placeholder: "john.doe@mcgill.ca", required: true, 
                     :'data-validation-email-message' => "Please enter a valid email", 
                     :'data-validation-regex-regex' => "^[a-zA-Z0-9\-]+\\.([a-zA-Z0-9]+\\.)?[a-zA-Z0-9\-]+(@mail.mcgill.ca|@mcgill.ca)$", 
                     :'data-validation-regex-message' => "Must be of the form firstname.lastname@mcgill.ca",
                     class: "input-xlarge newAdminEmail" %>
               </p>
            </fieldset>

            <fieldset name="addAdminID" class="control-group">
               <%= label_tag :student_id, "McGill Student ID", class: "cus-credit-card" %>
               <p class="controls">
                  <%= text_field_tag :student_id, nil, placeholder: "123456789", required: true, 
                                    :'data-validation-regex-regex' => "^[0-9]+$", 
                                    :'data-validation-regex-message' => "Student ID is incorrect format; must be a 9 digit number", 
                                    maxLength: "9",
                                    minLength: "9",
                                    placeholder: "123456789",
                                    class: "input-xlarge newAdminID" %>
               </p>
            </fieldset>

            <fieldset name="addAdminPassword" class="control-group">
               <%= label_tag :password, "McGill Password", class: "cus-lock" %>
               <p class="controls">
                  <%= password_field_tag :password, nil, required: true, 
                  minLength: "8",
                  :'data-validation-regex-regex' => "^[^\\s']+$", 
                  :'data-validation-regex-message' => "Password is incorrect format; cannot have any spaces or quotes(')", 
                  class: "input-xlarge newAdminPassword"%>
               </p>
            </fieldset>

            <fieldset name="addAdminConfirm" class="control-group">
               <%= label_tag :password_confirmation, "Confirmation", class: "cus-lock" %>
               <p class="controls">
                  <%= password_field_tag :password_confirmation, nil, 
                  :'data-validation-match-match' => "password", 
                  :'data-validation-match-message' => "Password confirmation must match password", 
                  class: "input-xlarge newAdminConfirm" %>
               </p>
            </fieldset>

            <fieldset name="submit">
               <%= button_tag(type: 'submit', class: "btn btn-large btn-inverse cus-ok") do %>
                  Create Account
               <% end %>
            </fieldset>
         <% end %>
      </section>
   </aside>
   <article class="span9">

      <ul class="users">
         <%= render @users %>
      </ul>

   </article>
</article>

app/views/users/new_notetaker.html.erb
<% provide(:title, 'NoteTaker Registration') %>
<%= render 'users/new', locals: { note_taker: true } %>

app/views/users/new_noteuser.html.erb
<% provide(:title, 'NoteUser Registration') %>
<%= render 'users/new', locals: { note_taker: false } %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<article class="row-fluid">
  <aside class="span4">
    <section>
      <h1>
        <% if current_user.admin? %>
          <%= link_to @user.name, edit_user_path(@user) %>
        <% else %>
          <%= @user.name %> 
        <% end %>
        |
        <strong class="text-success">
          <%= @user.student_id %>
        </strong>
        <p>
        (
        <% if @user.note_taker? %>
           <i class="icon-pencil icon-large"></i> NoteTaker
        <% elsif @user.admin?%>
           <i class="icon-gears icon-large"></i> Admin
        <% else %>
           <i class="icon-user icon-large"></i> NoteUser
        <% end %>)
        </p>
      </h1>
    </section>
  </aside>
  <article class="row-fluid">
    <% if current_user.admin? and not current_user?(@user) %>
    <section class="span6 well offset2">
    <%= form_for @user, url: registrations_path, method: :post, html: { class: "form-inline" } do |f| %>
     <legend>
        Register Courses You Are Enrolled In 
        <strong class="icon-question-sign icon-2x registerCourses pull-right"> Help</strong>
     </legend>
     <%= f.hidden_field :user, value: @user.id %>
     <fieldset name="search" class="control-group"> 
        <%= f.label :course_tokens, " Search", class: "icon-search" %>
        <%= f.text_field :course_tokens %> 
     </fieldset>

     <fieldset name="submit">     
        <%= button_tag type: 'submit', class: "btn btn-large btn-inverse icon-plus icon-large" do %>
           Register
        <% end %>
     </fieldset>
    <% end %>
  </section>
      <table cellpadding="1" cellspacing="1" class="table table-bordered table-hover">
       <caption class="alert alert-info"> 
          The course feed for the user
       </caption>
       <thead>
          <tr>
             <th class="sortable icon-sort-by-alphabet sorted-asc span2"> Term</th>
             <th class="sortable icon-sort-by-alphabet sorted-asc span2"> Course</th>
             <th class="span2 icon-unlink"> Unregister</th>
             <% if @user.note_taker? %>
              <th class="span2 icon-check"> Assign/Unassign </th>
            <% end %>
          </tr>
       </thead>
       <tbody>
          <% @user.registered_courses.each do |registered_course| %>
          <tr id="<%= registered_course.id %>" class="<%= @class %>">
            <td> 
              <p>
              <% if registered_course.term.upcase == "FALL" %>
                <%= fa_stacked_icon "leaf", base: "check-empty", class: "icon-2x text-error"%> 
              <% elsif registered_course.term.upcase == "WINTER" %>
                <%= fa_stacked_icon "asterisk", base: "check-empty", class: "icon-2x text-info" %>
              <% elsif registered_course.term.upcase == "SUMMER" %>
                <%= fa_stacked_icon "sun", class: "icon-2x text-warning" %>
              <% end %>
              <%= registered_course.term.upcase %>
              </p>
            </td>

            <td>
              <%= link_to "#{registered_course.subject_code} 
                       #{registered_course.course_num} 
                       #{registered_course.section}", registered_course %>
            </td>

            <td>
              <%= link_to registration_path(@user.registrations.find_by(course_id: registered_course), user: @user),
                data: { confirm: "Unregister #{@user.name} from the course: #{registered_course.term.upcase} | #{registered_course.subject_code} #{registered_course.course_num} #{registered_course.section} #{registered_course.course_title}?" }, method: :delete, class: "btn btn-small btn-danger" do %>
                <i class="icon-unlink icon-large"></i> Unregister
              <% end %>
            </td>
            <% if @user.note_taker? %>
              <td>
                <% if registered_course.note_taker.nil? %> 
                  <%= link_to course_path(registered_course, 
                       course: { user_id: @user }, user: @user ), method: :put, 
                       class: "btn btn-small btn-success" do %>
                    <i class="icon-check-empty icon-large"></i> Assign As Notetaker
                  <% end %>
                <% else %>
                  <% if registered_course.note_taker?(@user) %>
                    <%= link_to course_path(registered_course, 
                          course: { user_id: nil }, user: @user ), method: :put, 
                          class: "btn btn-small btn-success" do %>
                      <i class="icon-check icon-large"></i> UnAssign As Notetaker
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            <% end %>
          </tr>
          <% end %>
       </tbody>
    </table>
    <% else %>
      <div class="span8">
        <% if @user.notes.any? %>
          <h3>
            <%= pluralize(@user.notes.count, "Note") %> uploaded.
          </h3>
          <ol class="notes">
            <%= render @notes %>
          </ol>
          <%= will_paginate @notes %>
        <% end %>
      </div>
    <% end %>
  </article>
</article>

app/views/users/update.js.erb
$(".<%= user.id %>").html("<%= escape_javascript(link_to user.name, user) %>");
<% if user.approved? %> 
   $(".<%= user.id %>").append(" <%= escape_javascript(link_to 'Approved', user_path(user, user: { :approved => false }), method: :put, remote: true, class: 'approve icon-star icon-large') %>");
<% else %> 
   $(".<%= user.id %>").append(" <%= escape_javascript(link_to 'Unapproved',user_path(user, user: { :approved => true }), method: :put, remote: true, class: 'unapprove icon-star-empty icon-large') %>");
<% end %>