config/routes.rb
EZNotes::Application.routes.draw do
  resources :users 
  resources :sessions,  only: [:new, :create, :destroy]
  resources :notes,     only: [:create, :destroy]
  resources :courses,   only: [:show, :index, :create, :destroy, :update] 
  resources :course_imports, only: [:create, :new]
  resources :registrations, only: [:index, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update ]
  resources :accomodations, only: [:new, :create, :index]
  
  root to: 'static_pages#home'

  match '/notes/:id/:style.:extension', to: 'notes#download', via: 'get'

  match '/signup_noteuser',  to: 'users#new_noteuser',          via: 'get'
  match '/signup_notetaker',  to: 'users#new_notetaker',          via: 'get'
  match '/signin',  to: 'sessions#new',       via: 'get'
  match '/signout', to: 'sessions#destroy',   via: 'delete'
  match '/delete_all_courses', to: 'courses#delete_all_courses',        via: 'delete'
  match '/delete_accommodations', to: 'accomodations#delete_accommodations',        via: 'delete'

  match '/create_admin', to: 'users#create_admin',        via: 'put'

  match '/import_accomodations', to: 'accomodations#import', via: 'post'

  match '/help', to: 'static_pages#help',	via:'get'
  match '/about', to: 'static_pages#about',	via:'get'
  match '/contact', to: 'static_pages#contact',	via:'get'
end

app/views/shared/_add_course_form.html.erb
<%= form_for current_user, url: registrations_path, method: :post, html: { class: "form-inline" } do |f| %>
   <legend>
      Register Courses You Are Enrolled In 
      <strong class="icon-question-sign icon-2x registerCourses pull-right"> Help</strong>
   </legend>

   <fieldset name="search" class="control-group"> 
      <%= f.label :course_tokens, " Search", class: "icon-search" %>
      <%= f.text_field :course_tokens %> 
   </fieldset>

   <fieldset name="submit">     
      <%= button_tag type: 'submit', class: "btn btn-large btn-inverse icon-plus icon-large" do %>
         Register
      <% end %>
   </fieldset>
<% end %>

app/views/shared/_course_feed.html.erb
<% @user = current_user %>

<% if Time.now.month >= 1 and  Time.now.month < 9 %>
   <% fall_year = Time.now.prev_year.strftime("%Y") %>
   <% winter_year = Time.now.strftime("%Y") %>
   <% summer_year = Time.now.strftime("%Y") %>
<% elsif Time.now.month >= 9 and Time.now.month <= 12 %>
   <% fall_year = Time.now.strftime("%Y") %>
   <% winter_year = Time.now.strftime("%Y").next %>
   <% summer_year = Time.now.strftime("%Y").next %>
<% end %>

<header class="span12 header">
   <h4 class="center span4">
      <i class="icon-leaf text-error"></i> FALL (<%= fall_year %>)
   </h4>
   <h4 class="center span4"><i class="icon-asterisk text-info"></i> WINTER (<%= winter_year %>)</h4>
   <h4 class="center span4"><i class="icon-sun text-warning"></i>  SUMMER (<%= summer_year %>)</h4>
</header>
<section class="row-fluid body">
   <ul class="span4 fall">
      <%= render partial: 'shared/course_feed_item', collection: @fall_course_feed_items %>
   </ul>

   <ul class="span4 winter">
      <%= render partial: 'shared/course_feed_item', collection: @winter_course_feed_items %>
   </ul>

   <ul class="span4 summer">
      <%= render partial: 'shared/course_feed_item', collection: @summer_course_feed_items %>
   </ul>
</section>

app/views/shared/_course_feed_item.html.erb
<li class="row-fluid courseFeedItem">
  <section class="span6" id="<%= course_feed_item.id %>">
    <dl>
      <dt>
         <%= course_feed_item.subject_code %> 
         <%= course_feed_item.course_num %>
         <%= course_feed_item.section %>
      </dt> 
      <dd>
         <%= course_feed_item.course_title %>
      </dd>
    </dl>
    <section>
      <% if course_feed_item.note_taker?(current_user) and current_user.note_taker? %>
        <strong class="text-error">You are currently the note taker for this course.</strong>
      <% end %>
      <% if course_feed_item.note_taker and not current_user.note_taker? %>
        <strong class="text-error">NoteTaker: <%= course_feed_item.note_taker.email %></strong>
      <% end %>
    </section>
    <section class="timestamp">
      Registered <%= time_ago_in_words(@user.registrations.find_by(course_id: course_feed_item).created_at) %> ago.
    </section>
  </section>
  <section class="span6 courseFeedItemButtons">
    <%= link_to course_feed_item, class: "btn btn-medium btn-inverse" do %>
      <i class="icon-eye-open icon-large"></i> View Course
    <% end %>

    <% if @user.registered_with?(course_feed_item)%>
       <%= link_to registration_path(@user.registrations.find_by(course_id: course_feed_item), user: @user),
        data: { confirm: "Unregister from the course: #{course_feed_item.term.upcase} | #{course_feed_item.subject_code} #{course_feed_item.course_num} #{course_feed_item.section} #{course_feed_item.course_title}?" }, method: :delete, class: "btn btn-medium btn-danger" do %>
          <i class="icon-unlink icon-large"></i> Unregister
      <% end %>
    <% end %>
  </section>
</li>

app/views/shared/_delete_note_link.html.erb
<%= link_to "delete", object, method: :delete,
                              data: { confirm: "Are you sure?" },
                              title: object.lecture_title, class: "icon-trash delete" %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
   <ol class="notes">
      <%= render partial: 'shared/feed_item', collection: @feed_items %>
   </ol>
   <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
   <span class="title">
      <%= feed_item.lecture_title %>
   </span>
   <span class="date">
      <%= feed_item.lecture_date %>
   </span>
   <span class="comments">
      <%= wrap(feed_item.comments) %>
   </span>
   <span class="timestamp">
      Uploaded <%= time_ago_in_words(feed_item.created_at) %> ago.
   </span>
   <div class="center">
      <span class="download">
         <%= link_to('download file', feed_item.file.url, class: "icon-download download", alt: 'download', target: "_blank") %>
      </span> 
      <% if current_user?(feed_item.user) %>
         <%= render partial: 'shared/delete_note_link', locals: { object: feed_item } %>
      <% end %>
   </div>
</li>

app/views/shared/_not_signed_in.html.erb
<article class="center hero-unit">
   <section>
      <h1>Welcome to McGill OSD EZNotes</h1>   
      <h2 class="text-error"> The online service for uploading and accessing your course notes. </h2>
   
      <p class="alert alert-danger"> 
         Please register with the new <strong>2013</strong> system!
      </p>  
      <p class="alert alert-info">This site works best in Chrome web browser </p>
   </section>
   

   <section class="signupLinks">
      <%= link_to signup_notetaker_path, class: "btn btn-large btn-danger" do %>
         <i class="icon-pencil icon-large"></i> Register as a <em> NoteTaker </em>
      <% end %>   
      <%= link_to signup_noteuser_path, class: "btn btn-large btn-inverse" do %>
         <i class="icon-user icon-large"></i> Register as a <em> NoteUser </em>
      <% end %>
   </section>
         
</article>

app/views/shared/_note_form.html.erb
<%= form_for(@note) do |f| %>
   <%= render 'shared/error_messages', object: f.object %>
   <div><%= f.hidden_field :course_id, value: @course.id %></div>
   <div class="field">
      <%= f.label :file, class: "cus-attach" %>
      <%= f.file_field :file, accept: 'application/pdf, 
                                     application/msword, 
                                     application/vnd.openxmlformats-officedocument.wordprocessingml.document,
                                     image/png' %>
   </div>
   <div class="field">
      <%= f.label :lecture_title, "Lecture Title", class: "cus-pencil" %>
      <%= f.text_field :lecture_title, placeholder: "Lecture Title" %>
   </div>
   <div class="field">
      <%= f.label :lecture_date, "Lecture Date", class: "cus-check" %>
      <%= f.date_field :lecture_date %>
   </div>
   <div class="field">
      <%= f.label :comments, "Comments", class: "cus-comment-empty countdown" %>
      <%= f.text_area :comments, placeholder: "Comments" %>
   </div>
   <%= button_tag(type: 'submit', class: "btn btn-large btn-primary") do %>
      <i class="cus-upload"></i> Upload
   <% end %>
<% end %>

app/views/shared/_notetaker.html.erb
<p class="<%= notetaker.id %>" >
  <%= link_to notetaker.name, notetaker %> 
  <% if notetaker.approved? %>
    <%= link_to 'Approved', user_path(notetaker, user: { :approved => false }), method: :put, remote: true, class: "approve icon-star icon-large" %>
  <% else %>
    <%= link_to 'Unapproved',user_path(notetaker, user: { :approved => true }), method: :put, remote: true, class: "unapprove icon-star-empty icon-large" %> 
  <% end %>
</p>

app/views/shared/_registered_course.html.erb
<% @notetakers = registered_course.registered_users.where("note_taker = ?", true) %>
<% @noteusers = registered_course.registered_users.where("note_taker = ?", false) %>

<% if registered_course.note_taker %>
<% @class = "success"  %>
<% elsif @notetakers.empty? %>
<% @class = "error"  %>
<% else %>
<% @class = "warning"  %>
<% end %>

<tr id="<%= registered_course.id %>" class="<%= @class %>">
   <td><%= registered_course.term.upcase %></td>
   <td>
      <%= link_to "#{registered_course.subject_code} 
                   #{registered_course.course_num} 
                   #{registered_course.section}", 
                   registered_course %>
   </td>
   <td>
      <% if @noteusers.empty? %>
         0
      <% else %> 
        <strong class="muted"> <%= @noteusers.count %> registered </strong>
        <% @noteusers.each do |noteuser| %>
          <p> 
            <%= link_to noteuser.name, noteuser %> 
            <% if not Accomodation.exists?(student_id: noteuser.student_id) %>
              <small class="icon-warning-sign icon-large text-error"> not registered with OSD</small>
            <% end %>
          </p>
        <% end %>
      <% end %>
   </td>
   <td>
      <% if @notetakers.empty? %>
         0
      <% else %>
        <strong class="muted"> <%= @notetakers.count %> registered </strong>
        <%= render partial: 'shared/notetaker', collection: @notetakers %>
      <% end %>
   </td>
   <td>
      <% if registered_course.note_taker %>
        <strong class="muted"> 1 assigned </strong>
        <p>
          <%= link_to registered_course.note_taker.name, registered_course.note_taker %>
        </p>
      <% else %>
        None Assigned
      <% end %>
   </td>
</tr>

app/views/shared/_signed_in.html.erb
<% if current_user.admin? %>
   <aside class="row-fluid">
      <section class="span4">
         <%= render 'shared/user_info' %>
      </section>
   </aside>
   <article class="row-fluid">
      <section>
         <form class="form-search center">
            <input type="text" name="filter" value="" id="filter" class="input-xlarge search-query" />
            <label for="filter" class="icon-filter icon-large"> Filter</label>
         </form>
      </section>
      <%= render 'shared/admin_info' %>
   </article>
<% else %>
      
   <h2 class="alert alert-danger"> 
      <i class="icon-warning-sign"></i> 
      Once you have been matched for the courses you have registered for you will be notified by email with further instructions. 
      <i class="icon-warning-sign"></i>
   </h2>
      
   <aside class="row-fluid">
      <section class="span4">
         <%= render 'shared/user_info' %>
      </section>
      <section class="span6 well offset2">
         <%= render 'shared/add_course_form' %>
      </section>
   </aside>
   <% if @fall_course_feed_items.empty? and @winter_course_feed_items.empty? and @summer_course_feed_items.empty? %>
      <h1 class="alert alert-info"> No Classes Registered Yet </h1>
   <% else %>
      <article id="courseFeed" class="row-fluid">
         <%= render 'shared/course_feed' %>
      </article>   
   <% end %>        
<% end %>

app/views/shared/_stats.html.erb
<div class="stats">
   <strong id="noteusers" class="stat">
      <% @registered_note_users =  @course.registered_users.where("note_taker = ?", false) %>
      <% if @registered_note_users.count <= 1 %>
         <i class="icon-user"></i>
      <% elsif @registered_note_users.count > 1 %>
         <i class="icon-group"></i>
      <% end %>
      <%= pluralize(@registered_note_users.count, "noteuser") %>
      registered
   </strong>

   <strong id="notetakers" class="stat">
      <% @registered_note_takers =  
      @course.registered_users.count - @registered_note_users.count %>
      <% if @registered_note_takers <= 1 %>
         <i class="icon-user"></i>
      <% elsif @registered_note_takers > 1 %>
         <i class="icon-group"></i>
      <% end %>
      <%= pluralize(@registered_note_takers, "notetaker") %>
      registered
   </strong>

   <strong id="notetaker" class="stat">
      <i class="icon-pencil"></i>
      <% if @course.note_taker %>
         <%= pluralize(1, "notetaker") %>
      <% else %>
         <%= pluralize(0, "notetaker") %>
      <% end %>
      assigned
   </strong>
   
   <strong id="notes" class="stat">
      <% if @course.notes.count == 0 %>
         <i class="icon-file"></i>
      <% else %>
         <i class="icon-file-text"></i>
      <% end %>
      
      <%= pluralize(@course.notes.count, "note") %>
      uploaded
   </strong>
   
</div>

app/views/shared/_success_messages.html.erb
<% flash.each do |type, messages| %>
   <div class="alert <%= bootstrap_class_for(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
         <% if messages.is_a?(Array) %>
            <ul>
               <% messages.each do |message| %>
                  <li> <%= message %> </li>
               <% end %>
            </ul>
         <% else %>
            <%= messages %>
         <% end %>
   </div>
<% end %>

app/views/shared/_user_info.html.erb
<h1> <%= current_user.name.capitalize %> </h1>
<h4>
   (
   <% if current_user.note_taker? %>
      <strong><i class="icon-pencil icon-large"></i> NoteTaker</strong> 
   <% elsif current_user.admin?%>
      <strong><i class="icon-gears icon-large"></i> Admin</strong> 
   <% else %>
      <strong><i class="icon-user icon-large"></i> NoteUser</strong> 
   <% end %>)
</h4>
<p>
   <%= link_to current_user do %>
      <i class="icon-eye-open icon-large"></i> view my profile
   <% end %>
</p>
<% if not current_user.admin? %>
   <p id="registered_courses">
      <i class="icon-book icon-large"></i> Registered for <%= pluralize(current_user.registered_courses.count, "course") %>
   </p> 
<% end %>
<% if current_user.note_taker? %>
   <p id="notetaking_courses">
       <i class="icon-pencil icon-large"></i> Notetaking for <%= pluralize(current_user.notetaking_for.count, "course") %>
   </p>
   <p id="notes_uploaded">
      <i class="icon-file-text icon-large"></i> <%= pluralize(current_user.notes.count, "note") %> uploaded
   </p>
<% end %>