config/routes.rb
EZNotes::Application.routes.draw do
  resources :users 
  resources :sessions,  only: [:new, :create, :destroy]
  resources :notes,     only: [:create, :destroy]
  resources :courses,   only: [:show, :index, :create, :destroy, :update] 
  resources :course_imports, only: [:create, :new]
  resources :registrations, only: [:index, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update ]
  resources :accomodations, only: [:new, :create, :index]
  
  root to: 'static_pages#home'

  match '/notes/:id/:style.:extension', to: 'notes#download', via: 'get'

  match '/signup_noteuser',  to: 'users#new_noteuser',          via: 'get'
  match '/signup_notetaker',  to: 'users#new_notetaker',          via: 'get'
  match '/signin',  to: 'sessions#new',       via: 'get'
  match '/signout', to: 'sessions#destroy',   via: 'delete'
  match '/delete_all_courses', to: 'courses#delete_all_courses',        via: 'delete'
  match '/delete_accommodations', to: 'accomodations#delete_accommodations',        via: 'delete'

  match '/create_admin', to: 'users#create_admin',        via: 'put'

  match '/import_accomodations', to: 'accomodations#import', via: 'post'

  match '/help', to: 'static_pages#help',	via:'get'
  match '/about', to: 'static_pages#about',	via:'get'
  match '/contact', to: 'static_pages#contact',	via:'get'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://www.mcgill.ca/osd/"> McGill OSD </a>
		by OSD
	</small>
	<nav>
		<ul>
			<li>
				<%= link_to about_path, class: "icon-info-sign" do %>
					About
				<% end %>
			</li>
			<li>
				<%= link_to contact_path, class: "icon-envelope" do %>
					Contact
				<% end %>
			</li>
			<li><a href="http://www.mcgill.ca/osd/"> McGill OSD </a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container-fluid">
			<% homelink, otherlink = full_title(yield(:title)).split('|') %>
			<%= link_to homelink, root_path, id: "logo" %>
			<% if otherlink %>
				<%= link_to "|" + otherlink, request.path, id: "logo" %>
			<% end %>
			<nav>
				<ul class="nav pull-left">
					<% if not signed_in? and request.original_url == root_url %>
						<li>
							<%= form_for(:session, url: sessions_path, html: {class: "navbar-form"} ) do |f| %>
								<%= f.email_field :email, required: true, autofocus: true,
											:'data-validation-email-message' => "Please enter a valid email", 
											:'data-validation-regex-regex' => "^[a-zA-Z0-9\-]+\\.([a-zA-Z0-9]+\\.)?[a-zA-Z0-9\-]+(@mail.mcgill.ca|@mcgill.ca)$", 
											:'data-validation-regex-message' => "Must be of the form 
											firstname.lastname@mail.mcgill.ca or firstname.lastname@mcgill.ca",  placeholder: 'Mcgill Email', class: "input-large " %>

								<%= f.password_field :password, required: true, minLength: "8",
											:'data-validation-regex-regex' => "^[^\\s']+$", 
											:'data-validation-regex-message' => "Password is incorrect format; cannot have any spaces or quotes(')", placeholder: 'McGill password', class: "input-medium" %>

								<%= button_tag(type: 'submit', class: "btn btn-danger") do %>
										<i class="icon-signin icon-large"></i> Sign in
								<% end %>
							<% end %>
						</li>
						<li>
							<%= link_to new_password_reset_path do %>
							<i class="icon-unlock-alt icon-large"></i> Forgotten password? Click to reset
							<% end %>
						</li>
					<% end %>
				</ul>
				<ul class="nav pull-right">
					<li>
						<%= link_to root_path do %>
							<i class="icon-home icon-large"></i> Home
						<% end %>
					</li>
					<li>
						<%= link_to contact_path do %>
							<i class="icon-envelope icon-large"></i> Contact Us
						<% end %>
					</li>
					<li>
						<%= link_to help_path do %>
							<i class="icon-question-sign icon-large"></i> Help
						<% end %>
					</li>
					<% if signed_in? %>
						<% if  current_user.admin? %>
							<li id="fat-menu" class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="icon-group icon-large"></i> Users <b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li><%= link_to " Show Users", users_path, class: "icon-eye-open" %></li>
									<li><%= link_to " Download Matchings as CSV", courses_path(format: "csv"), class: "icon-download-alt" %></li>
								</ul>
							</li>
							
							<li id="fat-menu" class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="icon-book icon-large"></i> Courses <b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li><%= link_to " Show Courses", courses_path, class: "icon-eye-open" %></li>
									<li><%= link_to " Import Courses", new_course_import_path, class: "icon-upload-alt" %></li>
									<li class="divider"></li>
									<li><%= link_to " Delete All Courses", 'delete_all_courses', method: :delete, data: { confirm: "WARNING This will delete all courses hence will also delete all course registrations made by students and all notes associated with the course." },class: "icon-trash" %></li>
								</ul>
							</li>
							<li id="fat-menu" class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="icon-bar-chart icon-large"></i> Accommodations <b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li><%= link_to " Show Accommodations", accomodations_path, class: "icon-eye-open" %></li>
									<li><%= link_to " Import Accommodations", new_accomodation_path, class: "icon-upload-alt" %></li>
									<li class="divider"></li>
									<li><%= link_to " Delete All Accommodations", 'delete_accommodations', method: :delete, data: { confirm: "WARNING This will delete all accommodations!!!" },class: "icon-trash" %></li>
								</ul>
							</li>					
						<% end %>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="icon-cog icon-large"></i> Account <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to " Profile", current_user, class: "icon-user" %></li>
								<li><%= link_to " Settings", edit_user_path(current_user), class: "icon-edit" %></li>
								<li class="divider"></li>
								<li>
									<%= link_to " Sign out", signout_path, method: "delete", class: "icon-signout" %>
								</li>
							</ul>
						</li>
					<% else %>
						<li>
							<%= link_to signin_path do %>
								<i class="icon-signin icon-large"></i> Sign in 
							<% end %>
						</li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <%= stylesheet_link_tag    "application", media: "all",
	  															"data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container-fluid">
			<% flash.each do |key, value| %>
				<section class="alert alert-<%= key %>">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<%= content_tag(:section, value) %>
				</section>
			<% end %>
			<%= yield %>
		</div>
		<div class="container-fluid">
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>